secret deploy:
  stage: pre-deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo $ENV_SCOPE
    - sudo kubectl create secret docker-registry "$IMAGE_PULL_SECRET" --docker-server="$CI_REGISTRY" --docker-username="$REPOSITORY_USERNAME" --docker-password="$REPOSITORY_PASSWORD" --docker-email="$GITLAB_USER_EMAIL" --namespace="$NAMESPACE" -o yaml --dry-run=client | kubectl apply -f -; # gitlab registry 사용을 위한 secret 생성

  environment:
    name: $ENV_SCOPE
